NewsApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsApp.Data;
using NewsApp.Models;

namespace NewsApp.Controllers;

public class HomeController : Controller
{
    private readonly NewsAppDbContext _context;

    public HomeController(NewsAppDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var threeLastNews = await _context.NewsItems.OrderByDescending(x => x.Created).Take(3).ToListAsync();
        return View(threeLastNews);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    [HttpGet]
    [HttpPost]
    public IActionResult SetLanguage(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });
        
        return LocalRedirect(returnUrl);
    }
}

NewsApp/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsApp.Data;
using NewsApp.Models;
using NewsApp.ViewModels;

namespace NewsApp.Controllers;

public class NewsController : Controller
{
    private readonly NewsAppDbContext _context;
    private const int PageSize = 5;

    public NewsController(NewsAppDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        var news = await _context.NewsItems.ToListAsync();
        var items = news.Skip((page - 1) * PageSize).Take(PageSize).ToList();
        var pagingInfo = new PagingInfo()
        {
            CurrentPage = page,
            ItemsPerPage = PageSize,
            TotalItems = news.Count()
        };

        var viewModel = new IndexViewModel<NewsItem>()
        {
            Items = items,
            PagingInfo = pagingInfo
        };
        return View(viewModel);
    }

    public async Task<IActionResult> Details(Guid? id)
    {
        var news = await _context.NewsItems.FirstOrDefaultAsync(n => n.Id.Equals(id));
        return View(news);
    }

}

NewsApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model List<NewsItem>;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    @{
        if (Model.Count > 0)
        {
            <div class="row">
                @foreach (var newsItem in Model)
                {
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="@newsItem.PathToImage" alt="@newsItem.PathToImage">
                            <div class="card-body">
                                <h5 class="card-title">@newsItem.Title</h5>
                                <h6 class="card-subtitle mb-2 text-muted">@newsItem.SubTitle</h6>
                                <a class="btn btn-primary" asp-controller="News" asp-action="Details"
                                   asp-route-id="@newsItem.Id">@Localizer["Details"]</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    }
</div>